# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

#Trigger the workflow on push or pull request events
#on basically means on which event we need to apply this workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest #Github will run it on ubuntu-latest container

    steps:
        #Step1 - Checkout code from repository
        - name: Check out code
          uses: actions/checkout@v2
        
        #Step2 - Set up Python 3.10
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        #Step3 - Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        #Step4 Run tests
        - name: Run tests
          run: |
            pytest
